theme: jekyll-theme-slate
title: "Optimized flocking of autonomous drones in confined environments"
description: "G. Vásárhelyi, Cs. Virágh, G. Somorjai, T. Nepusz, A. E. Eiben, T. Vicsek, Science Robotics, 3, eaat3536 (2018)"
github:
  is_project_page: false
google_analytics: UA-122492266-1
