theme: jekyll-theme-slate
title: "Optimized flocking of autonomous drones in confined environments"
description: "G. Vásárhelyi, Cs. Virágh, G. Somorjai, T. Nepusz, A. E. Eiben, T. Vicsek, _Science Robotics_, **3**, eaat3536 (2018)"
